//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace skWebShell {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class system_const {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal system_const() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("skWebShell.system_const", typeof(system_const).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 function install_hook(elm){
        ///	$(elm).keyup(function(evt){
        ///		var $t = $(evt.currentTarget);
        ///		var tips = $t.data(&quot;tool&quot;);
        ///		if(tips == null){
        ///			tips = new ComboList($t);
        ///			$t.data(&quot;tool&quot;,tips);
        ///		}
        ///		tips.update($t.val());
        ///	});
        ///	$(elm).blur(function(evt){
        ///		var $t = $(evt.currentTarget);
        ///		var tips = $t.data(&quot;tool&quot;);
        ///		if(tips != null &amp;&amp; !tips.focused()){
        ///			tips.remove();
        ///		}
        ///	});
        ///	$(elm).focus(function(evt){
        ///		var $t = $(evt.currentTarget);
        ///		var tips = $t.data(&quot;tool&quot;);
        ///		if(tips == nu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cmp_idx {
            get {
                return ResourceManager.GetString("cmp_idx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ul li.list_item {
        ///  list-style-type:none;
        ///} 的本地化字符串。
        /// </summary>
        internal static string customized_css {
            get {
                return ResourceManager.GetString("customized_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*!
        /// * jQuery JavaScript Library v1.11.1
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2014-05-01T17:42Z
        /// */
        ///
        ///(function (global, factory) {
        ///
        ///    if (typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot;) {
        ///        // For CommonJS and CommonJS-like environments where a proper window is present,
        ///        // exe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_2_1_3_min {
            get {
                return ResourceManager.GetString("jquery_2_1_3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function install_hook(){
        ///	var mc = document.getElementById(&quot;fkfMc&quot;);
        ///	if (mc != null){
        ///		var onkeyup = mc.onkeyup;
        ///		mc.onkeyup = function(evt){onkeyup(evt);alert(&quot;OK&quot;)};
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string new_plugin_mc {
            get {
                return ResourceManager.GetString("new_plugin_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://127.0.0.1/public/jstest.html 的本地化字符串。
        /// </summary>
        internal static string service_url {
            get {
                return ResourceManager.GetString("service_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://aifapiao.duapp.com/public/index.php/fppos 的本地化字符串。
        /// </summary>
        internal static string service_url_1 {
            get {
                return ResourceManager.GetString("service_url_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function install_hook(){
        ///	alert(&quot;Test&quot;);
        ///} 的本地化字符串。
        /// </summary>
        internal static string test_js {
            get {
                return ResourceManager.GetString("test_js", resourceCulture);
            }
        }
    }
}
